---
- name: Update all packages
  dnf:
    name: "*"
    state: latest
    update_cache: yes
  tags: update

- name: Install required packages
  dnf:
    name:
      - python3
      - python3-pip
      - git
    state: present
  tags: packages

- name: Create application directory
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: dir

- name: Clone repository from GitHub
  git:
    repo: "{{ repo_url }}"
    dest: "{{ app_dir }}"
    version: main
    force: yes
  tags: clone

- name: Install Python dependencies
  pip:
    requirements: "{{ app_dir }}/requirements.txt"
    executable: pip3
  tags: pip

- name: Deploy systemd service
  template:
    src: server.service.j2
    dest: /etc/systemd/system/{{ service_name }}.service
    mode: 0644
  notify: Restart metrics service
  tags: service

- name: Enable and start service
  systemd:
    name: "{{ service_name }}"
    enabled: yes
    state: started
  tags: service
