---
- name: Update all packages
  dnf:
    name: "*"
    state: latest
    update_cache: yes
  tags: update

- name: Add Docker CE repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644
  tags: docker_repo
  become: yes

- name: Update DNF cache
  dnf:
    update_cache: yes
  tags: docker_repo
  become: yes

- name: Install Docker CE
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  tags: docker_install
  become: yes

- name: Install required packages
  dnf:
    name:
      - python3-pip
      - git
    state: present
  tags: packages


- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  tags: docker
  become: yes

- name: Create directory for Docker
  file:
    path: "{{ app_dir }}"
    state: directory
  tags: docker

- name: Copy Dockerfile
  copy:
    src: roles/container/files/Dockerfile
    dest: "{{ app_dir }}/Dockerfile"
  tags: docker

- name: Copy application code
  copy:
    src: roles/container/files/server.py
    dest: "{{ app_dir }}/server.py"
  tags: docker

- name: Copy dependencies
  copy:
    src: ../requirements.txt
    dest: "{{ app_dir }}/requirements.txt"
  tags: docker

- name: Install Python dependencies
  pip:
    requirements: "{{ app_dir }}/requirements.txt"
    executable: pip3
  tags: pip

- name: Build container image
  community.docker.docker_image:
    name: "metrics-server"
    tag: "latest"
    source: build
    build:
      path: "{{ app_dir }}"
    state: present
  tags: docker
  become: yes

- name: Run container
  community.docker.docker_container:
    name: metrics-server
    image: "metrics-server:latest"
    ports:
      - "8080:8080"
    state: started
    restart_policy: always
    detach: yes
  tags: docker
  become: yes
